name: TruffleHog Scan

on:
  push:
    branches:
      - '**'  # Run on all branches
  pull_request:
    branches:
      - '**'  # Run on all PRs

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    name: Run TruffleHog Scan

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure all history is fetched for scanning

      - name: Install TruffleHog
        run: |
          pip install --upgrade pip
          pip install trufflehog

      - name: Run TruffleHog
        run: |
          trufflehog filesystem --directory . --json > trufflehog-results.json

      - name: Show Scan Results
        if: always()  # Ensure this runs even if the previous step fails
        run: |
          if [ -s trufflehog-results.json ]; then
            echo "Secrets detected!"
            cat trufflehog-results.json
            exit 1
          else
            echo "No secrets detected."
          fi

      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: TruffleHog-Results
          path: trufflehog-results.json
